### ISSUE TITLE
bits/length attributes only support integer constants

### ISSUE THREAD

**Issue by andrewray** [xguerin/ppx_deriving_hardcaml#1]
The camlp4 extension allows arbitrary (integer typed) expressions when defining interfaces.

**Comment by xguerin** [comment]
I can easily forward any `Exp` passed into `[@bits]` and `[@length]` attributes. It would then be up to the compiler to make sure that these expressions are valid, integer typed expressions.

**Comment by andrewray** [comment]
Yup - that's what the camlp4 one did too.
