### ISSUE TITLE
Add method to pack and unpack interfaces

### ISSUE THREAD

**Issue by xguerin** [xguerin/ppx_deriving_hardcaml#10]
```ocaml
val pack : t I.t -> t
val unpack : t -> t I.t
```

**Comment by xguerin** [comment]
`pack` and `unpack` both use operations from `Comb.T`. Because of that dependency we should probably use a functor that takes a `Comb.T` as argument:

```ocaml
module S (B : HardCaml.Comb.T) : sig
  val pack : B.t t -> B.t
  val unpack : B.t -> B.t t
end
```

**Comment by andrewray** [comment]
It is relatively easy to derive extended functionality like this as things stand.  I have just committed a fairly large interface extension to HardCaml along these lines.  In use, it would look like

```
module X = struct type 'a t = { a : 'a; b : 'a }[@@deriving hardcaml] end

module Xx = HardCaml.Interface.Ex(X)
Xx.map3 (fun a b c -> ...) X.t { X.a=foo; b=bar } z

module Xxx = Xx.Make(Signal.Comb)
Xxx.pack { X.a = gnd; X.b = gnd }
```

There is perhaps some argument about the extra added module identifiers needed about which I am in two minds.  

Perhaps there is an arguent for `ppx_deriving_hardcaml` to have a code generation pattern like

```
module X = struct
  type 'a t = { .... } [@@deriving hardcaml extend=MyExt]
end
```

which produces

```
module Y : sig
  type 'a t = { a : 'a }[@@deriving hardcaml]
  module Ex : MyExt.Ex with type 'a t := 'a t 
end = struct
  type 'a t = { a : 'a }[@@deriving hardcaml]
  module Ex = MyExt.Ex(struct
      type 'a x = 'a t
      type 'a t = 'a x (* avoid cyclic type error *)
      let t = t
      let map = map
      let map2 = map2
      let to_list = to_list
  end) 
end
```

Then arbitrary extensions could be possible with a pattern of

```
module MyExt = struct
  module type Ex = sig 
    type 'a t  
    val ...   
  end
  module Ex(X : Interface.S) = struct 
    type 'a t = 'a X.t  
    let ...  
  end
end
```

**Comment by xguerin** [comment]
> I have just committed a fairly large interface extension to HardCaml along these lines

Indeed. These new features eluded me. And make this proposal obsolete.
