### ISSUE TITLE
Add support for user-defined interface extensions

### ISSUE THREAD

**Issue by xguerin** [xguerin/ppx_deriving_hardcaml#11]
From @andrewray - perhaps there is an argument for ppx_deriving_hardcaml to have a code generation pattern like:

```ocaml
module X = struct
  type 'a t = { .... } [@@deriving hardcaml extend=MyExt]
end
```

which produces:

```ocaml
module Y : sig
  type 'a t = { a : 'a }[@@deriving hardcaml]
  module Ex : MyExt.Ex with type 'a t := 'a t 
end = struct
  type 'a t = { a : 'a }[@@deriving hardcaml]
  module Ex = MyExt.Ex(struct
      type 'a x = 'a t
      type 'a t = 'a x (* avoid cyclic type error *)
      let t = t
      let map = map
      let map2 = map2
      let to_list = to_list
  end) 
end
```

Then arbitrary extensions could be possible with a pattern of:

```ocaml
module MyExt = struct
  module type Ex = sig 
    type 'a t  
    val ...   
  end
  module Ex(X : Interface.S) = struct 
    type 'a t = 'a X.t  
    let ...  
  end
end
```

**Comment by xguerin** [comment]
This would come really handy. As a matter of fact I have a couple of extensions to interfaces that could greatly benefit from this.

Given that an interface can have multiple extensions, I propose the following:

```ocaml
module X = struct
  type 'a t = { .... } [@@deriving hardcaml { extends = [ ("Ex", MyExt); ] } ]
end
```

**Comment by xguerin** [comment]
@andrewray it does not seem possible to use `Seq` constructs in extensions, right ? If we use an abstract type for the `Comb.S` component I am not quite sure how to make that work.

**Comment by andrewray** [comment]
Yes, `Comb.S` refers only to combinatorial logic.

When we functorize using `Comb.S` we are generally doing so to allow either `Signal.Comb` or `Bits.Comb.XXX` (and some others related to formal verification).

`Seq`(-uential) logic has no equivalent in the `Bits.Comb.XXX` world.

That being said, the underlying type for `Signal.Comb` and `Signal.Seq` is the same (`Signal.Types.signal`).

A possible pattern is:

```
module X = struct
  module Comb(B : Comb.S) = struct
     ..
  end
  module Signal = struct
    include Comb(Signal.Comb)
    (* add sequential constructs *)
    let reg ... = ...
  end
```

**Comment by xguerin** [comment]
Understood. In that case, wouldn't the proposed extension format be a bit too limiting ? For instance, I have a whole bunch of timing related operations (latch, reclock, pipeline, etc..) that I am applying at  the interface level. It would nicely fit the extension definition, but it would not apply because of its dependency to `Seq`.

**Comment by andrewray** [comment]
I can't see why it would be a problem.

Playing the new interface code in hardcaml (I can modify this to suit whatever scheme we eventually settle on) add the following definitions to Interface.Ex

```
(* signature *)
  val reg : Signal.Comb.t -> Signal.Comb.t t -> Signal.Comb.t t

(* implementation *)
  let reg e = map (Signal.Seq.(reg r_sync e))
```

And then in utop

```
#require "ppx_deriving_hardcaml";;

module Y : sig
  type 'a t = { a : 'a }[@@deriving hardcaml]
  module Ex : Interface.Ex with type 'a t := 'a t 
end = struct
  type 'a t = { a : 'a }[@@deriving hardcaml]
  module Ex = Interface.Ex(struct
      type 'a x = 'a t
      type 'a t = 'a x (* avoid cyclic type error *)
      let t = t
      let map = map
      let map2 = map2
      let to_list = to_list
  end) 
end

Y.Ex.reg enable (Y.map (fun (n,b) -> input n b) Y.t);;
```

**Comment by xguerin** [comment]
Indeed. My bad. I just needed to use the real type in my module signature.
