### ISSUE TITLE
Support for nested interfaces

### ISSUE THREAD

**Issue by andrewray** [xguerin/ppx_deriving_hardcaml#2]
```
module X = interface a b end
module Y = interface (x : X) c end
```

giving type `'a Y.t = { x : 'a X.t; c : 'a; }`

**Comment by xguerin** [comment]
Would a functor syntax be acceptable ?

```ocaml
module type X_t = sig
  type 'a t = {
    a : 'a;
    b : 'a
  } [@@deriving hardcaml]
end

module Y (X : X_t) = struct
  type 'a t = {
    x : 'a X.t;
    c : 'a;
  } [@@deriving hardcaml]
end
```

**Comment by andrewray** [comment]
Does it really help?  It seems the main thing to ensure/require is that the nested type is qualified by a module so you can look at `'a X.t` and extract the module part.  That's basically what the camlp4 one is doing so it can use it when generating calls to map (ie map calls map on the nested type and so on) etc.

**Comment by xguerin** [comment]
Probably not. I thought of the functor syntax as the interface syntax is parameterized.

**Comment by andrewray** [comment]
I think what you suggest is fine (and potentially useful), just not always necessary.  This is the same thing.

```
module X = struct
  type 'a t = {
    a : 'a;
    b : 'a
  } [@@deriving hardcaml]
end

module Y = struct
  type 'a t = {
    x : 'a X.t;
    c : 'a;
  } [@@deriving hardcaml]
end
```

Where the X comes from (a module in scope, or a functor argument) doesn't really matter.

**Comment by xguerin** [comment]
Gotcha.
